### PR TITLE
Fix for obfuscated dll (32bit)

### PR DESCRIPTION
**Pull request by ghost**
First of all run vars.bat or set KerbalHive=R:\KSP_1.3.1_dev
vars.bat should do that for you (permanently - setx).
Warning: Do not open the project before doing the above!

I had to change a lot of things to make it all working, take your time.
Can you test that in Linux? I would like to see KSP.log then.

### CODE REVIEW

**Comment by linuxgurugamer** [comment]
I will not accept any PRs which change my build scripts.

I also don't understand what you are talking about regarding an "obfuscated" dll

**Comment by linuxgurugamer** [comment]
I just read your other comment.

I suggest you take a look at Editor Extensions Redux to see how I deal which those sorts of Reflection values.
Keep in mind that the values change every release, which will require that this mod be changed every release if you start using numeric offsets.

**Comment by ghost** [comment]
1. You have hard-coded paths in the project as well (hints for assemblies, I couldn't compile it without changes, I have no R:\KSP_1.3.1_dev).
2. I have changed it in such a way, that it should work for both of us (now you don't even need to define KerbalHive, current .csproj can detect your paths or Steam automatically).
3. The code can autodetect any reflection (tested, just comment those three lines which try to find "\x1" and the following code will still find the fields). No need to change it anymore.
4. If you do not wish to support 32bit, then ok, no need to accept it at all, it does nothing else (well, it could make it work with Linux as well, but I don't know, cannot test that).
5. If you insist that no changes be made to build scripts and the .csproj itself (even if compatible and still working for both of us), then I can try to pull the only relevant .cs, but I had to change it so much (and clean to even understand what is going on), that you can do the same yourself, just take it from me.

The rest is up to you. If you ask for the simple pull, I will do it.

P.S.: Not sure what exactly are you thinking about in EER, but it seems you relay on the order of fields (get n-th no matter the name or type). I have used type detection (get first field of certain type).

**Comment by linuxgurugamer** [comment]
In eex, i have code which runs in debug mode to dump all the reflection offsets, which I then have to code in a special section since they arent available in Linux.
Which 3 lines.

**Comment by linuxgurugamer** [comment]
Please just do a simple commit & PR of the changed file, that will make it easier for me to review it.

I can't tell what's been changed when you do a web commit.

Thanks

**Pull request closed without merging**
