### PR TITLE
Fix for NullReference (in Start and Update)

### PR DESCRIPTION
**Pull request by ghost**
SafeCloneList => list == null ? null : new List(list)
+ usage of null-conditional like list?.Sort()

P.S.: Why is it not showing only differences? Problem with CR/LF and some GIT settings?

### CODE REVIEW

**Comment by ghost** [comment]
I am noob to Unity and KSP API, but I think the proper solution is completely different:
FlightGlobals.Vessels should be filtered by vessel.DiscoveryInfo.HaveKnowledgeAbout(DiscoveryLevels.StateVectors)
and you are done, you don't have to wait for SpaceTracking to create its list.

**Comment by linuxgurugamer** [comment]
Did you reformat the file?
What did you use to edit it?

**Comment by linuxgurugamer** [comment]
I merged this into a new branch where i will review the code.
Thanks

**Comment by ghost** [comment]
I have it in Visual Studio, but used Web for the commit.
The reason for it not working appears to be completely different:
It works in 64bit version (at least after my modification), but not in 32bit, because 32bit Assmebly-CSharp.dll is obfuscated and the addon cannot get the fields.

I will continue my work on it and commit when I have it,
but it required many changes because you have some paths hard-coded.
I will use environment variables (e.g. KerbalHive = path_to_KSP ... you have it on disk R),
that should allow us (and any other developer) work on it without having your mappings.

**Comment by linuxgurugamer** [comment]
I don't support 32 bit
The only paths I have hard-coded are in my build scripts, and those are not going to change.

You should not use the web for the commit because it will see every line as changed, and wastes my time, if you do that again, I'll just ignore it since I have a lot of other stuff to do.

There are only two places the path is hard-coded, in the deploy.bat and buildRelease.bat, it shouldn't be that difficult for you to change those two lines, and just not commit those files

Redo the obfuscated commit in a nicer format, and I will review it.

**Pull request merged**
